### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by vr8hub** [jnabholz/horatio-alger-jr_ragged-dick-or-street-life-in-new-york-with-the-bootblacks#1]
- [x] Can you update to the latest version of the tools (2.5.0), then copy the current version of core.css to <book directory>/src/epub/css/core.css?
- [x] se clean makes changes that should be accepted.
- [x] As does typogrify.
- [x] All of the `<!--end chapter-->` comments should be removed.
- [x] Commas (and periods) go inside quotes (in the US) regardless of why the quotes are there. The transcription was correct. Don’t forget to remove the ignore record.
- [x] The scan dedication is in small caps, I see no reason not to replicate that.
- [x] The book name in the preface, like all publication names, should be in italics and semanticated.
- [x] There’s a missing comma in chapter 1: there should be one after “don’t” in “If he don’t as is most likely…”. (Just happened to catch it while I was reading a few sentences.)
- [x] If it’s bootblack, I would think it’s also bootblacking; there is a boot-blacking in chapter 2.
- [x] The handbill in Chapter 5 should be in a blockquote, as should the advertisement in chapter 19. If there are others, they should be as well.
- [x] The play (Demon in the Danube) in Chapter 5 should be italicized and semanticated, as should any others that appear.
- [x] The newspaper headline in chapter 8 should be `<b>`, not `<strong>`. He’s not yelling the headline, just quoting it, so it just needs formatting, not extra emphasis.
- [x] The quantities in the table are numbers and therefore need to be right-justified. This means the unit-of-measure should be in its own `<td>`.
- [x] The valediction in the chapter-24 letter should be semanticated.
- [x] The valediction/signature in the letter in chapter 26 should be in a footer.
- [x] The blockquote in chapter-27 does not need a tag; the “title” attribute is for section titles, not blockquotes.
- [x] If the last block element in an endnote is a `<p>`, then the backlink goes at the end of that `<p>` [see SEMoS 7.10.5.2](https://standardebooks.org/manual/1.7.0/single-page#7.10.5.2). For example, the first endnote should be
````
<p>A fact. <a href="chapter-2.xhtml#noteref-1" epub:type="backlink">↩</a></p>
````
- [x] You don’t need both footer CSS’, just the general one; it covers all footers.
- [x] Likewise you don’t need two table CSS’, just the general one.
- [x] If a table is well within the margins, then we use `1em auto` to center it. We would only use just `1em` when the table is wide enough to extend to the left/right margins without it. (We should probably clarify that in SEMoS; I’ll look into that.)
- [x] The producer of the book is Andrew Sly (see [here](https://www.gutenberg.org/files/5348/5348-h/5348-h.htm)), and I see no mention of PGDP.
- [x] Also, the same page says the transcription was done in 2002, not 2004.
- [x] All names in the colophon that don’t have links should be `<b>` and semanticated, including yours; see [SEMoS 6.6.4.2](https://standardebooks.org/manual/1.7.0/single-page#6.6.4.2).
- [x] In the metadata, the main title contains only the title, not the subtitle. See [SEMoS 9.4.2](https://standardebooks.org/manual/1.7.0/single-page#9.4.2).
- [x] The book title in the colophon should also be just the main title.
- [ ] Ditto with the repository name (but don’t worry about it, Alex will fix it when he imports it into SE). The only places a book’s subtitle appears is in the metadata and, if there is one, the halftitle page.
